name: 'check-pr'
description: 'A composite action to check if an open pull request exists'

inputs:
  base_branch:
    description: 'Base branch to check for open pull requests'
    required: true
  head_branch:
    description: 'Head branch to check for open pull requests'
    required: true
  github_token:
    description: 'GitHub token to authenticate API requests'
    required: true

outputs:
  pr_number:
    description: 'The number of the open pull request or an empty string if none exists'
    value: ${{ steps.check.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Check for open pull requests
      id: check
      shell: bash
      run: |
        pr_number=$(gh pr list --state open --base ${{ inputs.base_branch }} --head ${{ inputs.head_branch }} --json number --jq '.[0].number')
        if [ -z "$pr_number" ]; then
          echo "No open pull requests found."
          echo "pr_number=" >> $GITHUB_OUTPUT
        else
          echo "Open pull request found: #$pr_number"
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
